# yaml-language-server: $schema=../node_modules/somod-schema/schemas/serverless-template/index.json

Resources:
  AjvLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      RetentionPolicy: Delete
      ContentUri:
        SOMOD::FunctionLayer:
          name: ajvLayer
          libraries:
            - decorated-ajv
  SomodWebSocketMiddleware:
    Type: SOMOD::Serverless::FunctionMiddleware
    SOMOD::Access: public
    Properties:
      CodeUri:
        SOMOD::FunctionMiddleware:
          name: websocketMiddleware
          allowedTypes:
            - WebSocket
      Layers:
        - SOMOD::Ref:
            resource: AjvLayer
